baseURL = "https://www.amosgross.com/"
languageCode = "en-us"
title = "Amos Gross"


[markup]
  [markup.highlight]
    anchorLineNos = false
    wrap = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "github"
    tabWidth = 4
    pygmentsUseClasses=true
