apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels: 
        app: homepage
    spec:
      containers:
        - image: registry.amosgross.com/ultra-homepage
          name: homepage
          ports:
            - containerPort: 80
              name: homepage
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  labels:
    app: homepage
spec:
  selector:
    app: homepage
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingressroutetls
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`www.amosgross.com`)
    kind: Rule
    services:
    - name: homepage-service
      port: 80
  tls:
    certResolver: myresolver
