# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
      - name: Build Hugo
        run: hugo --minify
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} docker login registry.amosgross.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t registry.amosgross.com/ultra-homepage:latest .
      - name: Push Docker Image
        run: docker push registry.amosgross.com/ultra-homepage:latest
      - name: Kube Update image
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: -n homepage set image deployment/homepage homepage=registry.amosgross.com/ultra-homepage
      - name: Kube Image Cleanup
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: -n homepage set image deployment/homepage homepage=registry.amosgross.com/ultra-homepage:latest
